/*

-- CREATE TABLE USERS (ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), USERNAME varchar(100), PASSWORD VARCHAR(100), PRIMARY KEY (ID));
-- CREATE TABLE QUIZ(ID BIGINT NOT NULL  GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), QUIZNAME varchar(100), PRIMARY KEY (ID));
-- CREATE TABLE QUESTION(ID BIGINT NOT NULL  GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), QUESTION_TEXT varchar(100), CORRECT_ANSWER BIGINT NOT NULL, PRIMARY KEY (ID));
-- CREATE TABLE ANSWER(ID BIGINT NOT NULL  GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), QUESTION_ID BIGINT NOT NULL, ANSWERTEXT varchar(100), PRIMARY KEY (ID));
-- 
*/