-- insert into USERS(id, USERNAME, PASSWORD) values (1, 'To Kill a MockingBird', 'PW')
-- insert into USERS(id, USERNAME, PASSWORD) values (2, 'James Bond', 'PW')
-- insert into USERS(id, USERNAME, PASSWORD) values (3, 'Intro to JEE7', 'PW')
-- 
-- insert into Quiz(id, QUIZNAME) values (1, 'Sample Quiz')
-- insert into Quiz(id, QUIZNAME) values (2, 'History Quiz')
