SELECT
'ALTER TABLE '||S.SCHEMANAME||'.'||T.TABLENAME||' DROP CONSTRAINT '||C.CONSTRAINTNAME||';'
FROM
SYS.SYSCONSTRAINTS C,
SYS.SYSSCHEMAS S,
SYS.SYSTABLES T
WHERE
C.SCHEMAID = S.SCHEMAID
AND
C.TABLEID = T.TABLEID
AND
S.SCHEMANAME = 'APP'
UNION
SELECT 'DROP TABLE ' || schemaname ||'.' || tablename || ';'
FROM SYS.SYSTABLES
INNER JOIN SYS.SYSSCHEMAS ON SYS.SYSTABLES.SCHEMAID = SYS.SYSSCHEMAS.SCHEMAID
where schemaname='APP';

ALTER TABLE APP.ANSWER DROP CONSTRAINT ANSWER_QUESTION_ID;
ALTER TABLE APP.ANSWER DROP CONSTRAINT SQL150421194118390;
ALTER TABLE APP.PLAYER DROP CONSTRAINT SQL150421194118580;
ALTER TABLE APP.QUESTION DROP CONSTRAINT QSTONCRRCTANSWERID;
ALTER TABLE APP.QUESTION DROP CONSTRAINT SQL150421194118300;
ALTER TABLE APP.QUIZ DROP CONSTRAINT SQL150421194118080;
ALTER TABLE APP.QUIZMATCH DROP CONSTRAINT QUIZMATCHPLAYER_ID;
ALTER TABLE APP.QUIZMATCH DROP CONSTRAINT QUIZMATCH_QUIZ_ID;
ALTER TABLE APP.QUIZMATCH DROP CONSTRAINT SQL150421194547540;
ALTER TABLE APP.QUIZMATCH_ANSWER DROP CONSTRAINT QZMTCHANSWERNSWRSD;
ALTER TABLE APP.QUIZMATCH_ANSWER DROP CONSTRAINT QZMTCHNSWERQZMTCHD;
ALTER TABLE APP.QUIZMATCH_ANSWER DROP CONSTRAINT SQL150421194547730;
ALTER TABLE APP.SEQUENCE DROP CONSTRAINT SQL150421194548090;
ALTER TABLE APP.USERS DROP CONSTRAINT SQL150421194547650;
DROP TABLE APP.ANSWER;
DROP TABLE APP.PLAYER;
DROP TABLE APP.QUESTION;
DROP TABLE APP.QUIZ;
DROP TABLE APP.QUIZMATCH;
DROP TABLE APP.QUIZMATCH_ANSWER;


